### ISSUE TITLE
AsyncTaskWithWaitingDialog.java line 57

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#32] opened 2015-10-01 11:05 UTC
#### in uk.ac.ucl.excites.sapelli.collector.util.AsyncTaskWithWaitingDialog.onPostExecute

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/560d1387f5d3a7f76b77b362](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/560d1387f5d3a7f76b77b362)

**BUILD_INFO**
*Built by mstevens on 2014-08-21 15:32:41 BST using master branch, revision 8f32c1d with changes*

**SAPELLI_DEVICE_ID_CRC32**
*1685678441* and *4136949986*

**Comment by mstevens83** [comment] 2015-10-05 13:41
Michalis or Julia, have you heard from Claire about this? I suspect this is happening on induction week phones. They should be using such an outdated version...
Anyway, this crash is similar to issue #28 which I think I fixed in a763b49. I can't be sure because I can't reproduce the crashes. But I think/hope the same fix will also resolve this other crash.

**Comment by mstevens83** [comment] 2015-10-05 15:54
Closing this because I believe that a763b49 resolves this problem, although it is hard to prove.

**Closed by mstevens83** 2015-10-05 15:54 UTC
