### ISSUE TITLE
ProjectManagerActivity.java line 431

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#30] opened 2015-10-01 10:58 UTC
#### in uk.ac.ucl.excites.sapelli.collector.activities.ProjectManagerActivity.populateProjectList

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/560d11c7f5d3a7f76b77a903](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/560d11c7f5d3a7f76b77a903)

**Comment by mstevens83** [comment] 2015-10-05 13:49
**BUILD_INFO**
*Built by mstevens on 2014-08-21 15:32:41 BST using master branch, revision 8f32c1d with changes*

Who is using this old version??

**Comment by mstevens83** [comment] 2015-10-05 14:12
The crash happens in `populateProjectList()` and is caused by an NPE, likely on `projectStore` or `projectList`. I don't get why either one would be `null` though...
`projectStore` is initialised in `onResume()` which calls `populateProjectList()` afterwards, and `projectList` is initialised in `onCreate()` which should also have been called before.

In any case, since the new project management UI introduced in beta16 all code relating to project list population has completely changed. So therefore this issue will most likely no surface again.

**Comment by mstevens83** [comment] 2016-01-05 11:34
This issue hasn't re-surfaced since the new project management UI was introduced in beta16, so can close this.

**Closed by mstevens83** 2016-01-05 11:34 UTC
